import { Customer } from "./types";

export const mockCustomers: Customer[] = Array.from({ length: 1000 }, (_, i) => ({
  id: i + 1,
  name: `Customer ${String(i + 1).padStart(2, '0')}`,
  title: ['CEO', 'CTO', 'CFO', 'COO'][i % 4], 
  address: `${100 + i * 10} ${['Business St', 'Tech Ave', 'Finance Blvd', 'Operations Rd'][i % 4]}, Suite ${100 + (i % 5) * 10}, ${['Cityville', 'Innovate City', 'Capital City', 'Logistics City'][i % 4]} Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum.`,
})) as Customer[];


export const queryArray = [
  "nature",
  "mountains",
  "fire",
  "oceans",
  "sunrise",
  "festivals",
  "technology",
  "hygiene",
  "animals",
  "cities",
  "space",
  "desert",
  "snow",
  "beach",
  "forest",
  "flowers",
  "architecture",
  "waterfalls",
  "sunsets",
  "nightlife",
  "sports",
  "travel",
  "food",
  "music",
  "art",
  "history",
  "vintage",
  "modern",
  "abstract",
  "patterns",
  "vehicles",
  "people",
  "pets",
  "events",
  "adventure",
  "landscapes",
  "urban",
  "rural",
  "seascapes",
  "mountain landscapes",
  "desert dunes",
  "wildlife",
  "underwater",
  "architecture",
  "interiors",
  "exteriors",
  "landmarks",
  "skyscrapers",
  "cityscapes",
  "rivers",
  "lakes",
  "glaciers",
  "sunrise",
  "sunset",
  "dawn",
  "dusk",
  "clouds",
  "rain",
  "storms",
  "fog",
  "mist",
  "lightning",
  "stars",
  "moon",
  "planets",
  "galaxies",
  "comets",
  "space stations",
  "satellites",
  "robots",
  "computers",
  "gadgets",
  "electronics",
  "machines",
  "artifacts",
  "crafts",
  "designs",
  "prints",
  "textures",
  "materials",
  "surfaces",
  "landforms",
  "patterns",
  "colors",
  "shapes",
  "shadows",
  "reflections",
  "symmetry",
  "asymmetry",
  "contrasts",
  "compositions",
  "shapes",
  "silhouettes",
  "motion",
  "stills",
  "close-ups",
  "landmarks",
  "historical sites",
  "natural wonders",
  "cultural heritage",
  "festivals",
  "ceremonies",
  "traditions",
  "customs",
  "rituals",
  "celebrations",
  "gatherings",
  "parties",
  "concerts",
  "performances",
  "theater",
  "dance",
  "music",
  "street art",
  "murals",
  "sculptures",
];

export {};
